# -*- coding: utf-8 -*-
"""Go to Page.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WLxRHn3feM9gr9AAdS2352QnOnf71jJ-
"""

###This function brings the page correspondent to a page number
###passed as input. Can be any integer number in the adequate interval.
###For example, if the script is currently in page 2, only 1 to 10 are
###valid values. If we are in page 33, only 31 to 40 are valid values.
def go_to_page(num):
  try:
    page_button = wd.find_element_by_xpath(f"//a[contains(@href,'ctl00$ctl52$g_a8f3fd9b_803d_47ef_8eab_9264b9b66cd7$ctl00$dpgResults$ctl00$ctl{num:02d}')]")
    page_button.click()
    WebDriverWait(wd, 10).until(EC.visibility_of_element_located((By.ID, 'ctl00_ctl52_g_a8f3fd9b_803d_47ef_8eab_9264b9b66cd7_ctl00_pnlUpdateProgress')))
    wd.save_screenshot("loading.png")
    WebDriverWait(wd, 20).until(EC.invisibility_of_element((By.ID, 'ctl00_ctl52_g_a8f3fd9b_803d_47ef_8eab_9264b9b66cd7_ctl00_pnlUpdateProgress')))
  except NoSuchElementException:
    raise Exception('No more pages to scrape...')